logging.config: classpath:logback-dev.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travis_monolith?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: ${JAVA_PROJECT_DEV_PASSWORD}

  mongodb:
    uri: mongodb://root:${JAVA_PROJECT_DEV_PASSWORD}@127.0.0.1:27017/travis_monolith?authSource=admin

application:
  external:
    #阿里云
    aliyun:
      #授权账户
      access-key:
        access-key-id: ${ALIYUN_ACCESSKEY_ID}
        access-key-secret: ${ALIYUN_ACCESSKEY_SECRET}
      #短信验证码
      authcode:
        domestic-template-code: ${ALIYUN_AUTHCODE_DOMESTIC_TEMPLATE_CODE}
        domestic-template-name: ${ALIYUN_AUTHCODE_DOMESTIC_TEMPLATE_NAME}
        international-template-code: ${ALIYUN_AUTHCODE_INTERNATIONAL_TEMPLATE_CODE}
        international-template-name: ${ALIYUN_AUTHCODE_INTERNATIONAL_TEMPLATE_NAME}
      #实名认证
      idcard:
        app-key: ${ALIYUN_IDCARD_APP_KEY}
        app-secret: ${ALIYUN_IDCARD_APP_SECRET}
        app-code: ${ALIYUN_IDCARD_APP_CODE}
    #支付宝
    alipay:
      app-id:
      app-private-key:
      alipay-public-key:
    #微信
    wx:
      #公众号
      mp:
        app-id:
        app-secret:
      #小程序
      miniapp:
        app-id:
        app-secret:
      #微信支付
      pay:
        mch-id:
        mch-key:
        key-path:
    #聚合数据
    juhe:
      #短信验证码
      authcode:
        app-key: ${JUHE_AUTHCODE_APP_KEY}
        tpl-id: ${JUHE_AUTHCODE_TPL_ID}
    #高德地图
    amap:
